spring.application.name=metrics-consumer

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
spring.kafka.consumer.group-id=metrics-consumer-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.metricsmonitoring.metricsconsumer.MetricEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=com.metricsmonitoring.metricsconsumer
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.listener.ack-mode=record

influxdb.url=${INFLUXDB_URL:http://influxdb:8086}
influxdb.org=${INFLUXDB_ORG:metrics-org}
influxdb.bucket=${INFLUXDB_BUCKET:metrics}
influxdb.token=${INFLUXDB_TOKEN}