apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: false
    uid: influxdb
    editable: false
    jsonData:
      version: Flux
      organization: metrics-org
      defaultBucket: metrics
    secureJsonData:
      token: $INFLUXDB_INIT_ADMIN_TOKEN